server:
  port: 3000
  error:
    inlcude-message: always
    include-binding-errors: always
    
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/my_crud
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: create-drop 
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect