logging:
  level:
    root: INFO
    web: DEBUG

server:
  port: 3000
  error:
    inlcude-message: ALWAYS
    include-exception: true
    whitelabel:
      enabled: false 

jwt:
  secret: "secret"
  expiration: 600000 # 10 min
  
redis:
  host: "127.0.0.1"
  port: 6379

spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:3306/my_crud
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate: 
      ddl-auto: create-drop 
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: monolegaltest@gmail.com
    password: monolegal123
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000